### ISSUE TITLE
Can't import pyLIMA.event or pyLIMA.microlmodels after installing with setup.py

### ISSUE THREAD

**Issue by shanencross** [ebachelet/pyLIMA#10]
pyLIMA works when I import it from a local folder, but not when installed as a package with setup.py.

I installed pyLIMA with "python setup.py install".

This worked, but when I try "from pyLIMA import microlmodels" I get (in ipython):

NameError                                 Traceback (most recent call last)
<ipython-input-10-16e122bd946d> in <module>()
----> 1 from pyLIMA import microlmodels

/home/scross/anaconda2/lib/python2.7/site-packages/pyLIMA-0.1-py2.7.egg/pyLIMA/microlmodels.pyc in <module>()
     35     print 'ERROR : No b0b1.dat file found, please check!'
     36 
---> 37 b0b1 = yoo_table
     38 zz = b0b1[:, 0]
     39 b0 = b0b1[:, 1]

NameError: name 'yoo_table' is not defined

I get a similar error for "from pyLIMA import event".

I looked at the installation folder (for me, "/home/scross/anaconda2/lib/python2.7/site-packages/pyLIMA-0.1-py2.7.egg/") and saw that the "pyLIMA/data" and "pyLIMA/test" folders were not installed there by setup.py!

pyLIMA/data contains Claret2011.fits and Yoo_B0B1.dat. I believe this error is from setup.py not installing the pyLIMA/data folder (maybe since they aren't python scripts).

**Comment by ebachelet** [comment]
Hi Shenan

Thanks for this. Martin is the person who can respond to this. But keep in
mind that pyLIMA is, not yet, really consider as a package (this is a
decision we made some time ago). The setup.py here is made to build on
Travis to make continuous integration.
But thank you for the try, I am pleased to see only this bug :)!

Cheers

2016-09-12 14:46 GMT-07:00 shanencross <notifications@github.com>:
