### ISSUE TITLE
AttributeError: type object 'parameters' has no attribute 'uo'

### ISSUE THREAD

**Issue by nrat** [ebachelet/pyLIMA#14]
I'm working through SAGAN_binary_3.ipynb. My version is attached. 

I've come across this error. In the code we initialise with some estimates for parameters:

> ### Have a look at your guess. Change these parameters if you want 
> estimate_parameters = [to, uo, tE, rho, np.log10(s), np.log10(q), alpha]
> 
> pyLIMA_parameters = binary_model.compute_pyLIMA_parameters(estimate_parameters)

Now if I try to print out uo from the estimate_parameters array, no problem:
 
> print(estimate_parameters[1])

0.4

.. as expected. If I try to print out the value of u0 from the pyLIMA_parameters object:

> print(pyLIMA_parameters.uo)

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-46-8b9775ca6ef0> in <module>()
>      38 
>      39 print(estimate_parameters[1])
> ---> 40 print(pyLIMA_parameters.uo)
>      41 
> 
> AttributeError: type object 'parameters' has no attribute 'uo'
> 

Not expected. Same issue for to .

The below reproduces the error. Any help?

Nick

import numpy as np
import matplotlib.pyplot as plt
import os, sys
import time
sys.path.append('/home/nicholas/CodeSpace/Microlensing/pyLIMA/')
sys.path.append('/home/nicholas/CodeSpace/')

from pyLIMA import event
from pyLIMA import telescopes
from pyLIMA import microlmodels
from pyLIMA import microlcaustics
from pyLIMA import microltoolbox
filename = './WFIRST_binary_SAGAN.dat'
###****ENDOFCHANGE****###
WFIRST_data = np.loadtxt(filename)

### Lets have a look at what it is exactly :
figure1 = plt.figure()
plt.errorbar(WFIRST_data[:,0]-2460000,WFIRST_data[:,1],yerr = WFIRST_data[:,2],fmt='.k')
plt.xlabel('HJD-2460000',fontsize=20)
plt.ylabel('MAG',fontsize=20)
plt.gca().invert_yaxis()
plt.show()
### if you do not have parameters estimations from the theory session.

###****CHANGE****###
### time when the anomaly occurs
t_anomaly = 2460930

### duration of the anomaly.
delta_t = 4.0
###****ENDOFCHANGE****###
### Insert the parameters you estimated here:

###****CHANGE****###
to = 2460956.448
uo = 0.4
tE = 35.0
rho = 0.000464
s = 1.2
q = 1*10**-3
alpha = -1.0

log_s = np.log10(s)
log_q = np.log10(q)
###****ENDOFCHANGE****###

### Create an event object. You can choose the name :

your_event = event.Event()

###****CHANGE****###
your_event.name = 'WFIRST binary'

### We define a telescope object.
wfirst = telescopes.Telescope(name='WFIRST', camera_filter='W149', light_curve_magnitude=WFIRST_data)
###****ENDOFCHANGE****###

your_event.telescopes.append(wfirst)
### Let's define a binary model, name in pyLIMA is Uniform Source Binary Lens.

binary_model = microlmodels.create_model('USBL', your_event)
binary_model.define_model_parameters()

### Have a look at your guess. Change these parameters if you want 
estimate_parameters = [to, uo, tE, rho, np.log10(s), np.log10(q), alpha]

pyLIMA_parameters = binary_model.compute_pyLIMA_parameters(estimate_parameters)

print(estimate_parameters[1])
print(pyLIMA_parameters.tE)

**Comment by ebachelet** [comment]
This is due to a recent push, changing the binary to, uo parameters to caustics definitions tc,uc. So it obviously crahes. It should be fixed now, since I came back to the standard names.
