### ISSUE TITLE
Pdb statement produced by microlsimulator

### ISSUE THREAD

**Issue by rachel3834** [ebachelet/pyLIMA#17]
Looks like there is an active Pdb line in this section of the code.  I agree this is extremely useful tool, but it should be active for development purposes only.  I suspect this error is caused by a badly-formed array of flux values.  It would be great to have an informative error message instead.

> /Users/rstreet/software/pyLIMA/pyLIMA/microlsimulator.py(340)simulate_lightcurve_flux()
-> flux_error = poisson_noise(theoritical_flux)
(Pdb)

**Comment by ebachelet** [comment]
Good catch. I agree with you with the error message, but is is difficult since it can come from various raions. I will think about it.

**Comment by ebachelet** [comment]
This is in principle fixed.
