### ISSUE TITLE
TypeError: differential_evolution() got an unexpected keyword argument 'atol' DE fit

### ISSUE THREAD

**Issue by blackmanjw** [ebachelet/pyLIMA#18]
With a fresh install of PyLIMA I get this error when trying to run a DE fit in the first jupyter notebook example. 

![screen shot 2018-01-03 at 13 47 39](https://user-images.githubusercontent.com/25968371/34507790-b5ea3680-f08d-11e7-9426-f7a912ac7a56.png)

**Comment by ebachelet** [comment]
This 'atol' parameter is only available on earlier version of scipy, please give a try to a scipy update.

**Comment by blackmanjw** [comment]
Thanks. The perils of having multiple python installs...

0.19.1 and above seem fine.
