### ISSUE TITLE
ImportError: undefined symbol: PyClass_Type

### ISSUE THREAD

**Issue by fbartolic** [ebachelet/pyLIMA#23]
I'm using `Python 3.6` and `swig 3.012`.  Here is a minimal example which reproduces the issue:
```
import sys
sys.path.append('path_to_pyLIMA')
import pyLIMA
from pyLIMA import event
```
Output:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-456f5cfa8d7c> in <module>()
----> 1 from pyLIMA import event

~/drive/projects/pyLIMA/pyLIMA/event.py in <module>()
     11 import numpy as np
     12 
---> 13 from pyLIMA import microlfits
     14 
     15 

~/drive/projects/pyLIMA/pyLIMA/microlfits.py in <module>()
     18 
     19 
---> 20 from pyLIMA import microlmodels
     21 from pyLIMA import microloutputs
     22 from pyLIMA import microlguess

~/drive/projects/pyLIMA/pyLIMA/microlmodels.py in <module>()
     21 
     22 from pyLIMA import microlguess
---> 23 from pyLIMA import microlmagnification
     24 from pyLIMA import microlpriors
     25 from pyLIMA import microlparallax

~/drive/projects/pyLIMA/pyLIMA/microlmagnification.py in <module>()
     10 
     11 
---> 12 from pyLIMA.subroutines.VBBinaryLensingLibrary import VBBinaryLensingLibrary as VBBinary
     13 
     14 

~/drive/projects/pyLIMA/pyLIMA/subroutines/VBBinaryLensingLibrary/VBBinaryLensingLibrary.py in <module>()
     26                 fp.close()
     27             return _mod
---> 28     _VBBinaryLensingLibrary = swig_import_helper()
     29     del swig_import_helper
     30 else:

~/drive/projects/pyLIMA/pyLIMA/subroutines/VBBinaryLensingLibrary/VBBinaryLensingLibrary.py in swig_import_helper()
     22         if fp is not None:
     23             try:
---> 24                 _mod = imp.load_module('_VBBinaryLensingLibrary', fp, pathname, description)
     25             finally:
     26                 fp.close()

~/anaconda3/lib/python3.6/imp.py in load_module(name, file, filename, details)
    241                 return load_dynamic(name, filename, opened_file)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:
    245         return load_package(name, filename)

~/anaconda3/lib/python3.6/imp.py in load_dynamic(name, path, file)
    341         spec = importlib.machinery.ModuleSpec(
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 
    345 else:

ImportError: /home/fran/drive/projects/pyLIMA/pyLIMA/subroutines/VBBinaryLensingLibrary/_VBBinaryLensingLibrary.so: undefined symbol: PyClass_Type

```
For now I'll just stick to Python 3.5 which works fine.

EDIT: correction, after installing several basic packages in my python 3.5 environment, I get the same error. Only Python 2.7 works properly.

**Comment by ebachelet** [comment]
OK thanks Fran. 

Could you try removing this : 
sys.path.append('path_to_pyLIMA').

**Comment by fbartolic** [comment]
Same error happens.

**Comment by ebachelet** [comment]
It might be related to : 
https://stackoverflow.com/questions/25188861/libboost-python3-so-1-56-0-undefined-symbol-pyclass-type
Could you check this? The python 3.5 building is working on TRAVIS.

**Comment by fbartolic** [comment]
No idea why it works with Travis. The problem is most likely related to SWIG building something against Python 2.7. When I run setup.py, I see this output:

`creating build/temp.linux-x86_64-2.7/pyLIMA/subroutines/VBBinaryLensingLibrary
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c ./pyLIMA/subroutines/VBBinaryLensingLibrary/VBBinaryLensingLibrary.cpp -o build/temp.linux-x86_64-2.7/./pyLIMA/subroutines/VBBinaryLensingLibrary/VBBinaryLensingLibrary.o
`
Not sure if it should be Python 3 there instead of 2.7, what do you get? 

I don't know how SWIG works, maybe there's a way to force it to build the VBB wrapper with Python 3?

**Comment by ebachelet** [comment]
Travis returns this
creating build/temp.linux-x86_64-3.5/pyLIMA/subroutines/VBBinaryLensingLibrary

So I guess your problem is there. Do you have swig install for python3.*?

This SWIG is really anoying, and I am wondering if we should not switch to another options your proposed in Auckland. Since I have to work on a branch for implementing VBB2.0 soon, this could be the good timing. Are you up for some help on this?

**Comment by fbartolic** [comment]
Hmmm, I have no idea how to force SWIG to use python 3, I've tried the `-py3` flag but it didn't do anything.  
> Do you have swig install for python3.*?

What do you mean by that?

I agree that SWIG is annoying, I've looked into options for interfacing C++ code with Python. First I thought about `ctypes` because that's what I've used in the past but it looks like it doesn't work with C++ libraries. Then I came across `pybind11` (https://pybind11.readthedocs.io/en/stable/) . I think this is the best option. Also, the LSST Data Management team decided to switch from SWIG to pybind11 (https://pybind11.readthedocs.io/en/stable/) and they have a huge codebase of  mostly Python and C++ code that needs to talk to each other. They also provided some guidelines here: https://developer.lsst.io/coding/python_wrappers_for_cpp_with_pybind11.html

I could help by figuring out how to wrap VBB 2.0 with this, it shouldn't be too complicated I think. What kind of time frame did you have in mind? I'm currently interfacing VBB 2.0 with a NS sampler but both are written in C++ so I didn't need to write a Python wrapper.

**Comment by ebachelet** [comment]
I mean that maybe you swig is installed for python2 but not python3.0

I also find this pybind11 package and I think this is a good option, which gonna need some  effort. I would like to do this asap, probably starting next week. I will let you know.

**Comment by ebachelet** [comment]
This is solved with the separate VBB installation.
