### ISSUE TITLE
Sagan binary notebook issue

### ISSUE THREAD

**Issue by tmesh** [ebachelet/pyLIMA#24]
I have installed pyLIMA and am going through the Sagan workshop Wednesday hands on session. I noticed the SAGAN_binary_3 notebook fails at "import check". Is this a function which has been written for pyLIMA? I can't find it online or in this repository. Thanks for your help!

**Comment by ebachelet** [comment]
Hi Tiffany

You right, this function is not part of pyLIMA. It was specially designed to the SAGAN workshop. 
If you send me an email to etibachelet@gmail.com, I can provide it to you.
