### ISSUE TITLE
mpi4py 3.0 - AttributeError: 'mpi4py.MPI.Pickle' object attribute 'dumps' is read-only.

### ISSUE THREAD

**Issue by blackmanjw** [ebachelet/pyLIMA#29]
With mpi4py 3.0 the following error occurs when trying to run MCMC with mpirun:

AttributeError: 'mpi4py.MPI.Pickle' object attribute 'dumps' is read-only.

I fixed this by changing 

```
  MPI.pickle.dumps = dill.dumps
  MPI.pickle.loads = dill.loads
```

to `MPI.pickle.__init__(dill.dumps, dill.loads)`

in microlfits.py

as per https://stackoverflow.com/questions/21779541/mpi4py-replace-built-in-serialization

**Comment by rachel3834** [comment]
I see this error also and can confirm that this fix works.

**Comment by rachel3834** [comment]
Many thanks for the feedback @blackmanjw

**Comment by ebachelet** [comment]
Done.
