### ISSUE TITLE
TypeError: differential_evolution() got an unexpected keyword argument 'workers'

### ISSUE THREAD

**Issue by lisadang27** [ebachelet/pyLIMA#35]
Hello, 
I just installed pyLIMA a couple of days ago and am running the examples for the first time.
I get the following error 
TypeError: differential_evolution() got an unexpected keyword argument 'workers'
<img width="840" alt="screen shot 2019-02-04 at 1 07 35 pm" src="https://user-images.githubusercontent.com/17075772/52240579-1421d100-2886-11e9-9c4f-8a95cef17bc3.png">

**Comment by kswnin** [comment]
Check your scipy version number using:
print(scipy.__version__)

"workers" was introduced in 1.2.0!

**Comment by ebachelet** [comment]
Yes, this will be implemented in the requirements.txt. Thanks for the spotting @lisadang27 and for the help @kswnin .I think we can close it now.
