### ISSUE TITLE
Need help: Generating Lightcurves

### ISSUE THREAD

**Issue by lisadang27** [ebachelet/pyLIMA#37]
Hello, 
I am trying to generate lightcurves for an event as seen from 2 observatories, Earth and Spitzer. I am not trying to fit any data.

I was wondering if it would be possible to add a tutorial for simply generating lightcurves, i.e. no fitting involve or noise simulation. 

Thanks!
Lisa

**Comment by rachel3834** [comment]
Hi Lisa, 

You can certainly simulate lightcurves from Earth and Spitzer.  We have a Python notebook tutorial for this if you look [here](https://github.com/ebachelet/pyLIMA/blob/master/examples/pyLIMA_example_3.ipynb).  

In box 6 you will see some text showing you how to adapt this example to simulate lightcurves from a space-based observatory.  Although the example given is Gaia, pyLIMA can handle any spacecraft for which it can get ephemeris information - including Spitzer.  

All you have to do is change the name of the spacecraft to be the name recognized by the JPL Horizons system, which in this case I think is "Spitzer Space Telescope" (though please check this!).  

pyLIMA will do a live-lookup from JPL Horizons for you, or you can download the observer-format table data and include it directly.  

I hope this helps!

**Comment by lisadang27** [comment]
Hi Rachel! 
Thanks for the response, this is very helpful!
I was hoping there would be an option to turn off the white (poisson) noise as well.
Thanks!

**Comment by rachel3834** [comment]
Hi Lisa, 

Sounds like the easiest option for you would be to use the pyLIMA's function for computing the microlensing magnification, which can of course easily be converted into flux or magnitudes. 

Here's an example code to guide you.  I seem to be having trouble contacting JPL Horizons system, so I suggest you use the online interface to generate the ephemeris table for Spitzer, then load it (see the commented-out text).  

Hope this helps!
[simulate_spitzer_earth_lens.py.gz](https://github.com/ebachelet/pyLIMA/files/2943831/simulate_spitzer_earth_lens.py.gz)

**Comment by ebachelet** [comment]
Hi Lisa

Thanks for the contribution. Is it working for you now?
