### ISSUE TITLE
PSPL with parallax fit failure

### ISSUE THREAD

**Issue by Nijaid** [ebachelet/pyLIMA#38]
When fitting a PSPL event with parallax using Earth and Space telescopes, the DE method fails to give a sensible solution, converging upon something with parameters way off from the non-parallax with LM fit, even outputting 'nan' for the parameter errors. How can I start looking for what is going wrong? If it's of any help, the Space data is mostly at the event peak, while the Earth data covers the peak and baseline. Also, the Space data is entered in as flux rather than magnitude.

**Comment by ebachelet** [comment]
Hi Nijaid.

Do you have a subset of the code ? There is several points where it could go wrong :

- did you specify the Space telescope loacation as 'Space'? Did you give also the spacecraft_name?
- did you ingest the space data as flux rather than in mah?

**Comment by Nijaid** [comment]
Here is my input. From what I can see, I did follow those specifications.

`ogle = telescopes.Telescope(name='OGLE', camera_filter='I', light_curve_magnitude=ogle_dat)
myevent.telescopes.append(ogle)
spitz3[:, 0] += 2450000.0 # pyLIMA requires HJD
spitzer = telescopes.Telescope(name='SPITZER', camera_filter='IRAC1',light_curve_flux=spitz3)
spitzer.location = 'Space'
spitzer.spacecraft_name = 'Spitzer'
myevent.telescopes.append(spitzer)
`

**Comment by ebachelet** [comment]
Try with lightcurve_magnitude and lightcurve_flux instead of light_curve_magnitude and light_curve_flux

**Comment by Nijaid** [comment]
`light_curve_magnitude`and `light_curve_flux` are the keywords for initializing the telescope object, though. Do you mean specifying it after initialization?

**Comment by Nijaid** [comment]
If I try `telescopes.Telescope(name='OGLE', camera_filter='I', lightcurve_magnitude=ogle_dat)` I get `TypeError: __init__() got an unexpected keyword argument 'lightcurve_magnitude'`

**Comment by ebachelet** [comment]
Ah yes sorry you right, forgot what I said.
What are the format of your Spitzer flux? If this is difference flux (i.e you have some negative values) you might want to add a reference_flux to obtain positive values. Also, you can set clean_the_lightcurve='No' to avoid automatic outlier rejection.

**Comment by Nijaid** [comment]
The flux is in arbitrary units, but they're all positive. I also tried turning off the cleaning, but obtained the same results.

**Comment by ebachelet** [comment]
Did you set the event.ra and event.dec?

Also, what is you DE_population? What is your parallax model? Did you set t0_par close to the event peak?

**Comment by Nijaid** [comment]
I did set the RA and DEC, although I didn't show it when copying the code above. The parallax model is 'Full' and I set t0_par as the rounded value of the non-parallax fit t0, as was done in Example 5.

**Comment by ebachelet** [comment]
Hi Nijaid

If you send me the materials you use, I can have a closer look to what went
wrong.

Cheers

**Comment by Nijaid** [comment]
Sure, could you let me know the email to send it to? Thank you very much
for working on this.

**Comment by ebachelet** [comment]
etibachelet@gmail.com

**Comment by ebachelet** [comment]
Is this resolve now?

**Comment by Nijaid** [comment]
It is! Thank you for letting me know how to constrain the parameters.

**Comment by ebachelet** [comment]
For the record, to constrain a parameter i for the DE fit:

Model.parameters_boundaries[i] = [min_i,max_i]
