### ISSUE TITLE
Running pyLIMA under windows

### ISSUE THREAD

**Issue by mpgh** [ebachelet/pyLIMA#40]
The text suggests that pyLIMA runs "Successfully test on various UNIX, MAC and Windows". A complete, successful installation requires a fortran compiler for pyslalib and to compile VBBinaryLensing under windows. For some users it might be worth to point out that using Linux in a VirtualBox under Windows might be an easier option.

**Comment by ebachelet** [comment]
Should be fixed with 1.9
