### ISSUE TITLE
MCMC plots in branch LeeFSPL

### ISSUE THREAD

**Issue by mpgh** [ebachelet/pyLIMA#41]
Running MCMC under the LeeFSPL branch returns:

/anaconda3/lib/python3.7/site-packages/pyLIMA-0.1.5-py3.7.egg/pyLIMA/microloutputs.py in fit_outputs(fit)
    271
    272     figure_trajectory = plot_geometry(fit)
--> 273     figure_table = parameters_table(fit)
    274
    275

~/anaconda3/lib/python3.7/site-packages/pyLIMA-0.1.5-py3.7.egg/pyLIMA/microloutputs.py in parameters_table(fit)
    956                      + [0.0]]
    957
--> 958     table_val = np.round(table_val, 5).tolist()
    959     table_val = np.array(table_val).T.tolist()
    960

~/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py in round_(a, decimals, out)
   3380     around : equivalent function; see for details.
   3381     """
-> 3382     return around(a, decimals=decimals, out=out)
   3383
   3384

~/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py in around(a, decimals, out)
   3005
   3006     """
-> 3007     return _wrapfunc(a, 'round', decimals=decimals, out=out)
   3008
   3009

~/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     64     # a downstream library like 'pandas'.
     65     except (AttributeError, TypeError):
---> 66         return _wrapit(obj, method, *args, **kwds)
     67
     68

~/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapit(obj, method, *args, **kwds)
     44     except AttributeError:
     45         wrap = None
---> 46     result = getattr(asarray(obj), method)(*args, **kwds)
     47     if wrap:
     48         if not isinstance(result, mu.ndarray):

TypeError: can't multiply sequence by non-int of type 'float'

**Comment by ebachelet** [comment]
New push should have fixed this. If it is, please close.
