### ISSUE TITLE
Key error:photometry (space data) in branch Rebranding

### ISSUE THREAD

**Issue by mpgh** [ebachelet/pyLIMA#59]
When initialising a PSPLmodel for space-born Gaia data, we are experiencing the key error: photometry. 
Please find below the traceback:

pspl = PSPL_model.PSPLmodel(gaia_event, parallax=['Full', t0ref])
in MLmodel.__init__(self, event, parallax, xallarap, orbital_motion, blend_flux_parameter, origin, fancy_parameters)
--> 116 self.define_pyLIMA_standard_parameters()
in MLmodel.define_pyLIMA_standard_parameters(self)
--> 187 self.second_order_model_parameters(model_dictionnary_updated)
in MLmodel.second_order_model_parameters(self, model_dictionnary)
--> 270     self.event.compute_parallax_all_telescopes(self.parallax_model)
in Event.compute_parallax_all_telescopes(self, parallax_model)
--> 158     telescope.compute_parallax(parallax_model, self.North, self.East, self.ra*np.pi/180)
in Telescope.compute_parallax(self, parallax_model, North_vector, East_vector, right_ascension)
--> 311     parallax.parallax_combination(self, parallax_model, North_vector, East_vector, right_ascension)
in parallax_combination(telescope, parallax_model, North_vector, East_vector, right_ascension)
    197 if (parallax_model[0] == 'Terrestrial') | (telescope.location == 'Space'):
--> 199         telescope_positions = -telescope.telescope_positions[data_type]
    200         delta_North += np.dot(telescope_positions, North_vector)
KeyError: 'photometry'

**Comment by ebachelet** [comment]
I believe this is fixed with the latest pushed?

**Comment by mpgh** [comment]
This is correct and occurred because of missing the new telescope syntax.
