### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by giordano** [ebachelet/pyLIMA#6]
This project claims to be "[open source](https://en.wikipedia.org/wiki/Open-source_software)", but it misses a license, so it isn't so.  The availability of the code [doesn't mean it's "open source"](https://en.wikipedia.org/wiki/Open-source_software#Open-source_vs._source-available), while being an important requirement.  Without a license, it misses most points of [Open Source Definition](https://opensource.org/osd-annotated) by the Open Source Initiative, most notably points 1 and 3, free redistribution and derived works, as [no license implies](http://choosealicense.com/licenses/no-license/) modification and redistribution are forbidden.

A software without a license and written by someone whose origin Country is member of the [Berne Convention](http://www.wipo.int/treaties/en/text.jsp?file_id=283698) is by copyrighted by default: the authors retain all rights for them.  This is in contrast with any [definition](https://en.wikipedia.org/wiki/Open-source_software#Definitions) of "open source".

So, please, pick up a license.  [Here](http://choosealicense.com/licenses/) is a list of common licenses, with descriptions.  I'd personally recommend you to choose the GPL license, but the decision is up to you.  For example, the [General Complex Polynomial Root Solver](http://www.astrouw.edu.pl/~jskowron/cmplx_roots_sg/) written by Skowron & Gould is released under terms of LGPL & Apache licenses.  It may also be worth mentioning that a widespread astronomical package written in Python, Astropy, is released under the terms of New BSD license, instead.

**Comment by ebachelet** [comment]
We have a license now, can this be closed?

**Comment by giordano** [comment]
Yes, sure
