### ISSUE TITLE
satellite_positions using ephemerides from a file

### ISSUE THREAD

**Issue by anibal-art** [ebachelet/pyLIMA#61]
Hello, I'm receiving the error I paste at the bottom of the post when I want to fit a light curve using ephemerides in this format `ephemerides = np.array([[ 2.46035088e+06,  7.75136400e+01,  1.33979800e+01,
         1.03741560e-03],
       [ 2.46035188e+06,  8.53436100e+01,  1.42240000e+01,
         1.97349720e-03],
       [ 2.46035288e+06,  8.86030300e+01,  1.45353100e+01,
         2.67562680e-03],
       ...,
       [ 2.46499988e+06,  3.50649550e+02, -3.18034000e+00,
         1.07762928e-02],
       [ 2.46500088e+06,  3.51059600e+02, -2.82885000e+00,
         1.07786088e-02],
       [ 2.46500188e+06,  3.51471720e+02, -2.47674000e+00,
         1.07819004e-02]])`
it's an array of 4 columns and n rows. I'm adding this using the syntax `tel1.spacecraft_positions ={'astrometry':[],'photometry':ephemerides}`. The way I make the code pass this error is changing in the parallax.py file, in the function "space_ephemerides" the line that defines satellite_positions in this way: `satellite_positions = np.array(spacecraft_positions).item()['photometry']`.

The error
`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[6], line 15
     13 tinit = time.time()
     14 # fit_2, e, tel_list= fit_light_curve(ruta+'Event_'+str(i)+'.txt',False)
---> 15 fit_2, e, tel_list = fit_light_curve(ruta+'Event_'+str(i)+'.txt',False,'TRF')
     17 tfin = time.time()
     18 print(tfin-tinit)

Cell In[5], line 21, in fit_light_curve(file_name, binning, algo)
     18 te = PARAMS['te']
     19 model_type = 'PSBL'
---> 21 fit_2, e, tel_list = fit_event_model(PARAMS['Source'],PARAMS,algo, model_type, array_w149, array_u, array_g, array_r, array_i, array_z, array_y)
     22 fit_2, e, tel_list = fit_event_roman(PARAMS['Source'],PARAMS,algo, model_type, array_w149)
     23 return fit_2, e, tel_list

Cell In[3], line 129, in fit_event_model(n, event_params, algo, model_type, wfirst_lc, lsst_u, lsst_g, lsst_r, lsst_i, lsst_z, lsst_y)
    125 else:
    127     e.check_event()
--> 129     psbl = PSBL_model.PSBLmodel(e, parallax=['Full', event_params['t0']])
    131     # Give the model initial guess values somewhere near their actual values so that the fit doesn't take all day
    132     lensing_parameters = [float(event_params['t0']), float(event_params['u0']), float(event_params['te']), 
    133                               float(event_params['s']),float(event_params['q']),float(event_params['alpha']), float(event_params['piEN']), float(event_params['piEE'])]

File ~/.conda/envs/pyLIMAv2/lib/python3.9/site-packages/pyLIMA/models/USBL_model.py:14, in USBLmodel.__init__(self, event, parallax, xallarap, orbital_motion, blend_flux_parameter, origin, fancy_parameters)
      9 def __init__(self, event, parallax=['None', 0.0], xallarap=['None'],
     10              orbital_motion=['None', 0.0], blend_flux_parameter='fblend',
     11              origin=['center_of_mass', [0, 0]], fancy_parameters={}):
     12     """The fit class has to be intialized with an event object."""
---> 14     super().__init__(event, parallax=parallax, xallarap=xallarap,
     15                      orbital_motion=orbital_motion,
     16                      blend_flux_parameter=blend_flux_parameter, origin=origin,
     17                      fancy_parameters=fancy_parameters)

File ~/.conda/envs/pyLIMAv2/lib/python3.9/site-packages/pyLIMA/models/ML_model.py:81, in MLmodel.__init__(self, event, parallax, xallarap, orbital_motion, blend_flux_parameter, origin, fancy_parameters)
     78 self.origin = origin
     80 self.check_data_in_event()
---> 81 self.define_pyLIMA_standard_parameters()
     82 self.define_fancy_parameters()

File ~/.conda/envs/pyLIMAv2/lib/python3.9/site-packages/pyLIMA/models/ML_model.py:238, in MLmodel.define_pyLIMA_standard_parameters(self)
    234 model_dictionnary = self.paczynski_model_parameters()
    236 model_dictionnary_updated = self.astrometric_model_parameters(model_dictionnary)
--> 238 self.second_order_model_parameters(model_dictionnary_updated)
    240 self.telescopes_fluxes_model_parameters(model_dictionnary_updated)
    242 self.pyLIMA_standards_dictionnary = OrderedDict(
    243     sorted(model_dictionnary_updated.items(), key=lambda x: x[1]))

File ~/.conda/envs/pyLIMAv2/lib/python3.9/site-packages/pyLIMA/models/ML_model.py:370, in MLmodel.second_order_model_parameters(self, model_dictionnary)
    367     model_dictionnary['piEN'] = len(model_dictionnary)
    368     model_dictionnary['piEE'] = len(model_dictionnary)
--> 370     self.event.compute_parallax_all_telescopes(self.parallax_model)
    372 if self.orbital_motion_model[0] == '2D':
    373     jack = 'Numerical'

File ~/.conda/envs/pyLIMAv2/lib/python3.9/site-packages/pyLIMA/event.py:135, in Event.compute_parallax_all_telescopes(self, parallax_model)
    126 """
    127 Launch the parallax computation for all telescopes
    128 
   (...)
    131 parallax_model : list, [str,float] the parallax model
    132 """
    134 for telescope in self.telescopes:
--> 135     telescope.compute_parallax(parallax_model, self.North, self.East)

File ~/.conda/envs/pyLIMAv2/lib/python3.9/site-packages/pyLIMA/telescopes.py:347, in Telescope.compute_parallax(self, parallax_model, North_vector, East_vector)
    335 def compute_parallax(self, parallax_model, North_vector, East_vector):
    336     """
    337     Compute and set the deltas_positions attributes according to the parallax model.
    338 
   (...)
    345     details in microlparallax module.
    346     """
--> 347     self.initialize_positions()
    348     parallax.parallax_combination(self, parallax_model, North_vector,
    349                                   East_vector)  # , right_ascension)
    350     print('Parallax(' + parallax_model[
    351         0] + ') estimated for the telescope ' + self.name + ': SUCCESS')

File ~/.conda/envs/pyLIMAv2/lib/python3.9/site-packages/pyLIMA/telescopes.py:230, in Telescope.initialize_positions(self)
    226 self.find_Earth_positions()
    228 if self.location == 'Space':
--> 230     self.find_space_positions()
    232 else:
    234     self.find_sidereal_time()

File ~/.conda/envs/pyLIMAv2/lib/python3.9/site-packages/pyLIMA/telescopes.py:328, in Telescope.find_space_positions(self)
    325 if data is not None:
    326     time = data['time'].value
--> 328     satellite_positions, space_positions = parallax.space_ephemerides(self,
    329                                                                       time,
    330                                                                       data_type=data_type)
    332     self.telescope_positions[data_type] = satellite_positions
    333     self.spacecraft_positions = space_positions

File ~/.conda/envs/pyLIMAv2/lib/python3.9/site-packages/pyLIMA/parallax/parallax.py:189, in space_ephemerides(telescope, time_to_treat, data_type)
    187 satellite_positions = np.array(spacecraft_positions)
    188 #print(satellite_positions.item()['photometry'])
--> 189 dates = satellite_positions[:, 0].astype(float)
    190 ra = satellite_positions[:, 1].astype(float)
    191 dec = satellite_positions[:, 2].astype(float)

IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed`

**Comment by ebachelet** [comment]
Thanks for reporting. I tried a test case to replicate your issue:

`
from pyLIMA import telescopes
import numpy as np

ephemerides = np.array([[ 2.46035088e+06,  7.75136400e+01,  1.33979800e+01, 1.03741560e-03], [ 2.46035188e+06,  8.53436100e+01,  1.42240000e+01, 1.97349720e-03], [ 2.46035288e+06,  8.86030300e+01,  1.45353100e+01, 2.67562680e-03]])
lc = np.c_[ephemerides[:,0],[18.2,18.3,18.4],[0.01,0.02,0.03]]
tel = telescopes.Telescope(name='Roman',camera_filter='W149',light_curve=lc,light_curve_names=['time', 'mag', 'err_mag'], light_curve_units=['JD', 'mag', 'mag'],location='Space',spacecraft_name='Roman')
tel.spacecraft_positions ={'astrometry':[],'photometry':ephemerides}
tel.initialize_positions()
`
This runs fine. Can you try this code to see if it works for you?

**Comment by anibal-art** [comment]
Ok, that example works after re-install pyLIMA and the error dissapear. So I'm closing the issue. Thank you
