### ISSUE TITLE
Possible installation issue

### ISSUE THREAD

**Issue by rojofija** [ebachelet/pyLIMA#64]
Hi.

I would like to report a possible issue during the installation procedure.

In a virtual environment using python 3.11.3 in Linux Debian 11.7, I tried:

python -m pip install -U pip  status: (ok)

pip install -U pyLIMA

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
panel 1.1.0 requires bokeh<3.2.0,>=3.1.1, but you have bokeh 2.4.3 which is incompatible.

python3 -m pip install 'bokeh>=3.1.1,<3.2.0'

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pylima 1.9 requires bokeh<3, but you have bokeh 3.1.1 which is incompatible.

So, I decided to use git:

git clone https://github.com/ebachelet/pyLIMA.git

cd pyLIMA/
pip install .    -status: Successfully installed pyLIMA-1.9

All the best.
Rojofija.

**Comment by ebachelet** [comment]
I believe this is fixed?
