### ISSUE TITLE
fsbl TypeError

### ISSUE THREAD

**Issue by blackmanjw** [ebachelet/pyLIMA#65]
Unsure if this is an error on my part of a bug, but when I try to run

print(fsbl.find_telescopes_fluxes(my_fit12.fit_results['best_model']))

or

pyLIMA_plots.plot_lightcurves(fsbl, my_fit12.fit_results['best_model’])

after a successful fsbl DE fit, I get this error:

![Screenshot 2023-07-19 at 14 00 20](https://github.com/ebachelet/pyLIMA/assets/25968371/2677deb3-93b8-464d-bc61-08bc90d1805a)

**Comment by ebachelet** [comment]
I believe this is fixed?
