### ISSUE TITLE
noblend option returns variable dfluxdfs referenced before assignment

### ISSUE THREAD

**Issue by mpgh** [ebachelet/pyLIMA#68]
When fitting an event via TRF

pspl = PSPL_model.PSPLmodel(test_event, parallax=['None', t0guess], blend_flux_parameter='noblend')
pspl.define_model_parameters()
fit_tap = TRF_fit.TRFfit(pspl)    
[...]
fit_tap.fit()

the following issue appears:
...
in MLmodel.photometric_model_Jacobian(self, telescope, pyLIMA_parameters)
    170     dfluxdg = [1] * len(amplification)
    172 # breakpoint()
--> 173 jacobi = np.c_[magnification_jacobian, dfluxdfs, dfluxdg].T
    174 return jacobi

UnboundLocalError: local variable 'dfluxdfs' referenced before assignment

**Comment by ebachelet** [comment]
This is now fixed on 1.9.1 It is not deployed on pip so please close and install the repository (pip install .)
