### ISSUE TITLE
Feature request: loss functions part of the (default) cost function

### ISSUE THREAD

**Issue by mpgh** [ebachelet/pyLIMA#69]
To fit non-PSPL models with a PSPL fit (e.g. via TRF), more robust techniques would be helpful. For this purpose, the commonly used loss functions soft_l1 and or huber (e.g. iminuit or as part of https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html) would help get closer to a predictive trajectory.

**Comment by ebachelet** [comment]
This now implemented, one can choose between loss_function = 'chi2', 'likelihood' or 'soft_l1'
