### ISSUE TITLE
Negative fluxes: ValueError: lam < 0 or lam contains NaNs

### ISSUE THREAD

**Issue by anibal-art** [ebachelet/pyLIMA#73]
Hello, I have this issue with a simulation on pyLIMA. When I run this code I see that if I simulate the telescope without using baseline magnitudes as do in the second block an error arise asociated to negative fluxes simulated by pyLIMA. After a investigation I realize that if I comment the line 
`simulator.simulate_lightcurve_flux(my_own_model, pyLIMA_parameters_1)`
and use baseline magnitude and then run `simulator.simulate_lightcurve_flux(my_own_model, pyLIMA_parameters_1)` the problem is solved. For further details see this notebook

https://github.com/anibal-art/roman_rubin/blob/main/issue_pyLIMA/issue_pyLIMA.ipynb

Best regards,
Anibal

**Comment by ebachelet** [comment]
Hello Anibal

What fluxes are you giving to your my_own_parameters  array? I can not see fromm the attached figure.

**Comment by anibal-art** [comment]
Hello, I'm not giving flux parameters in the first block of the notebook. Is that a problem ?

**Comment by ebachelet** [comment]
Yes you need to gives source and blend flux for all telescope before simulating the lightcurves!

**Comment by ebachelet** [comment]
I believe this is closed?
