### ISSUE TITLE
Scipy will remove `misc.derivative` function in future version

### ISSUE THREAD

**Issue by ketozhang** [ebachelet/pyLIMA#75]
> DeprecationWarning: scipy.misc.derivative is deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. You may consider using findiff: https://github.com/maroba/findiff or numdifftools: https://github.com/pbrod/numdifftools

Not too bad to accomodate, there's only one usage of this function:
https://github.com/search?q=repo%3Aebachelet%2FpyLIMA%20misc.derivative&type=code

**Comment by ebachelet** [comment]
Thanks for reporting. It is updated in 1.9.2 just pushed on pip and tagged here
