### ISSUE TITLE
MCMC convergence and mixing depends on eps parameter

### ISSUE THREAD

**Issue by mpgh** [ebachelet/pyLIMA#81]
The epsilon parameter "eps" defning the cloud of start walkers as part of MCMC_fit.py line 58 can lead to poor mixing of chains. In many cases a smaller eps like 1e-2 would be more appropriate to keep chains in the vicinity of the best solution. The uniform distribution also contributes to runaway chains. I would suggest to either reduce it or better make it a user parameter.

**Comment by ebachelet** [comment]
Good catch Markus, I probably did this for some reasons but I will revert it.

**Comment by ebachelet** [comment]
I believe this is fixed now
